trigger:
- main  # Le pipeline s'exécute automatiquement sur la branche principale.

pool: default  

steps:

# Étape 1 : Déploiement des ressources Azure 
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Deploy TP2 Azure Resources"
  inputs:
    deploymentScope: 'Resource Group'  
    azureResourceManagerConnection: 'Azure subscription 1(ed84d7cb-a009-41e8-9f67-6bad56b8d14e)'  
    subscriptionId: 'ed84d7cb-a009-41e8-9f67-6bad56b8d14e'  
    action: 'Create Or Update Resource Group'  
    resourceGroupName: 'Ressource_groupe2'  
    location: 'West Europe'  # .
    templateLocation: 'Linked artifact'  
    csmFile: '$(System.DefaultWorkingDirectory)/TP2_Azure/azuredeploy.json'  
    csmParametersFile: '$(System.DefaultWorkingDirectory)/TP2_Azure/azuredeploy.parameters.json'  
    deploymentMode: 'Incremental'  

# Étape 2 : Déploiement des ressources nécessaires pour la Function App
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Function Deployment"
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(ed84d7cb-a009-41e8-9f67-6bad56b8d14e)'  # Connexion valide pour le déploiement.
    subscriptionId: 'ed84d7cb-a009-41e8-9f67-6bad56b8d14e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RessourceGroupe'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ProjetFunctionApp/azuredeploy.json'  # Chemin corrigé vers le fichier modèle.
    csmParametersFile: '$(System.DefaultWorkingDirectory)/ProjetFunctionApp/azuredeploy.parameters.json'  # Chemin corrigé vers les paramètres.
    deploymentMode: 'Incremental'


# Étape 1 : Installation du SDK .NET
- task: UseDotNet@2
  displayName: "Install .NET SDK"
  inputs:
    packageType: 'sdk'
    version: '6.x'  # Remplacez par la version spécifique.

# Étape 3 : Restauration des dépendances
- task: DotNetCoreCLI@2
  displayName: "Restore Project"
  inputs:
    command: 'restore'
    projects: '$(System.DefaultWorkingDirectory)/TP2_Azure/FunctionApp2/FunctionApp2.csproj'

# Étape 4 : Compilation du projet
- task: DotNetCoreCLI@2
  displayName: "Build Azure Function"
  inputs:
    command: 'build'
    projects: '$(System.DefaultWorkingDirectory)/TP2_Azure/FunctionApp2/FunctionApp2.csproj'  
    arguments: '--configuration Release --output $(Build.BinariesDirectory)'

# Étape 5 : Publication du projet
- task: DotNetCoreCLI@2
  displayName: "Publish Azure Function"
  inputs:
    command: 'publish'
    projects: '$(System.DefaultWorkingDirectory)/TP2_Azure/FunctionApp2/FunctionApp2.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true
    modifyOutputPath: false

# Étape 6 : Publication des artefacts générés
- task: PublishBuildArtifacts@1
  displayName: "Publish Build Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
