trigger:
- main  # Le pipeline s'exécute automatiquement sur la branche principale.

pool: default  

steps:

# Étape 1 : Déploiement des ressources Azure 
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Deploy TP2 Azure Resources"
  inputs:
    deploymentScope: 'Resource Group'  
    azureResourceManagerConnection: 'Azure subscription 1(ed84d7cb-a009-41e8-9f67-6bad56b8d14e)'  
    subscriptionId: 'ed84d7cb-a009-41e8-9f67-6bad56b8d14e'  
    action: 'Create Or Update Resource Group'  
    resourceGroupName: 'Ressource_groupe2'  
    location: 'West Europe'  # .
    templateLocation: 'Linked artifact'  
    csmFile: '$(System.DefaultWorkingDirectory)/TP2_Azure/azuredeploy.json'  
    csmParametersFile: '$(System.DefaultWorkingDirectory)/TP2_Azure/azuredeploy.parameters.json'  
    deploymentMode: 'Incremental'  

# Étape 2 : Déploiement des ressources nécessaires pour la Function App
- task: AzureResourceManagerTemplateDeployment@3
  displayName: "Function Deployment"
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(ed84d7cb-a009-41e8-9f67-6bad56b8d14e)'  # Connexion valide pour le déploiement.
    subscriptionId: 'ed84d7cb-a009-41e8-9f67-6bad56b8d14e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RessourceGroupe'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ProjetFunctionApp/azuredeploy.json'  # Chemin corrigé vers le fichier modèle.
    csmParametersFile: '$(System.DefaultWorkingDirectory)/ProjetFunctionApp/azuredeploy.parameters.json'  # Chemin corrigé vers les paramètres.
    deploymentMode: 'Incremental'


