# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: default

steps:


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(ed84d7cb-a009-41e8-9f67-6bad56b8d14e)'
    subscriptionId: 'ed84d7cb-a009-41e8-9f67-6bad56b8d14e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Ressource_groupe2'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\TP2_Azure\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\TP2_Azure\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure subscription 1(1)(ed84d7cb-a009-41e8-9f67-6bad56b8d14e)'
    subscriptionId: 'ed84d7cb-a009-41e8-9f67-6bad56b8d14e'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RessourceGroupe'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)\ProjetFunctionApp\azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)\ProjetFunctionApp\azuredeploy.parameters.json'
    deploymentMode: 'Incremental'
  displayName: Function Deployment


- job: FunctionBuild
  displayName: Function Build

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore Project
    inputs:
      command: 'restore'
      projects: '$(Build.SourcesDirectory)/$(ProjetFunctionApp)/*.csproj'
      
  - task: DotNetCoreCLI@2
    displayName: Build Azure Function
    inputs:
      command: 'build'
      projects: '$(Build.SourcesDirectory)/$(ProjetFunctionApp)/*.csproj'
      arguments: '--configuration Release --output $(Build.BinariesDirectory)'

  - task: DotNetCoreCLI@2
    displayName: Publish Azure Function
    inputs:
      command: 'publish'
      projects: '$(Build.SourcesDirectory)/$(ProjetFunctionApp)/*.csproj'
      arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
      publishWebProjects: false
      zipAfterPublish: true
      modifyOutputPath: false
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'

     - job: FunctionDeploy    